version: '3'
services:
  app1:
    image: linhtran2023/create-link-url-shop:v02
    container_name: app1
    ports:
      - "8080:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`create-short-link.realdealvn.click`)"
      - "traefik.http.services.app1.loadbalancer.server.port=8080"

  app2:
    image: linhtran2023/redirecr-url-shop:v01
    container_name: app2
    ports:
      - "8081:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`trum-riviu.realdealvn.click`)"
      - "traefik.http.services.app2.loadbalancer.server.port=8081"

  proxy:
    image: traefik:v2.5
    container_name: proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
